In [43]:
import numpy as np
 
class Perceptron(object):

    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
    
  
    def activation_fn(self, x):
        return 1 if x >= 0 else 0    
    
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)
                


In [44]:
 X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
d = np.array([0, 0, 0, 1])
 



In [45]:
d

array([0, 0, 0, 1])

In [46]:
perceptron = Perceptron(input_size=2)

In [47]:
perceptron.W

array([0., 0., 0.])

In [48]:
perceptron.fit(X, d)
print(perceptron.W)

[-3.  2.  1.]


In [49]:
mp=Perceptron(5)
x=np.asarray([-10,2,-30,4,-50])
mp.predict(x)

1

In [50]:

mp.activation_fn(-1)

0

In [51]:
mp.W

array([0., 0., 0., 0., 0., 0.])

In [11]:
# 1. soru                
"""
 a)   def __init__(self, input_size, lr=1, epochs=10):
         Bu fonksiyon constructor fonksiyon. Nesne oluşturulunca çalışır. lr ve epochs değişkenlerine varsayılan değerler olarak atanmış.
         W parametresine ise 0'lardan oluşan bir dizi atıyoruz. Boyutuna +1 eklememizin sebebi sapmayı da hesaba katıyor olmamız.

         learning rate(LR): Her dolaşımda düzeltilecek olan miktarı kısıtlamak için kullanılır

         epochs: veri setinin kaç kere dolaşılacağını belirtir.
     
 b)  def activation_fn(self, x):
            
         Bu fonksyion kendisine gelen x değerini kontrol ediyor. Veri setini 2'ye ayırıyor. Eğer x>0 ise 1 değilse 0 döndürüyor.

 c)
      def predict(self, x):
           
        x değerinin 0. elemanına 1 koyuyor ve bunu W transpozesi ile dot product işlemine sokuyor. Oluşan çıktıyı activation_fn
        fonksiyonuna gönderip dönen değeri döndürüyor
        
  d)
       def fit(self, X, d):
            
            xin içindeki tüm verileri dolaşıp e=d[i]-y yaparak error(e) buluyoruz 
            Ve son satırdaki W değerini error kullanarak yeniden oluşturuyoruz.
         

"""

"\n a)   def __init__(self, input_size, lr=1, epochs=10):\n         Bu fonksiyon constructor fonksiyon. Nesne oluşturulunca çalışır. lr ve epochs değişkenlerine varsayılan değerler olarak atanmış.\n         W parametresine ise 0'lardan oluşan bir dizi atıyoruz. Boyutuna +1 eklememizin sebebi sapmayı da hesaba katıyor olmamız.\n\n         learning rate(LR): Her dolaşımda düzeltilecek olan miktarı kısıtlamak için kullanılır\n\n         epochs: veri setinin kaç kere dolaşılacağını belirtir.\n     \n b)  def activation_fn(self, x) \n            \n         Bu fonksyion kendisine gelen x değerini kontrol ediyor. Veri setini 2'ye ayırıyor. Eğer x>0 ise 1 değilse 0 döndürüyor.\n\n c)\n      def predict(self, x)\n           \n        x değerinin 0. elemanına 1 koyuyor ve bunu W transpozesi ile dot product işlemine sokuyor. Oluşan çıktıyı activation_fn\n        fonksiyonuna gönderip dönen değeri döndürüyor\n        \n  d)\n       def fit(self, X, d)\n            \n            xin içindeki tüm ve

In [52]:
# 2. soru 
d2 = np.array([0, 0, 1, 1]) 
perceptron2 = Perceptron(input_size=2)
perceptron2.W
perceptron2.fit(X, d2)
perceptron2.W

array([-1.,  1.,  0.])

In [ ]:
# 4. soru 

"""
Fonksiyonumuzdaki hata istenen değer ve elimizdeki sonuç arasındaki fark anlamına gelir.

"""